### ISSUE TITLE
implement a proper interface for the 2d camera

### ISSUE THREAD

**Issue by touchportyl** [WLVerse/FlexEngine#43]
Refer to #41 and #42. This interface will be used in the scripting layer.

Default behavior
- camera will never move if there is no target entity or position
- camera spawns 3 units away from [0, 0, 0] zoomed in to an average level
- camera spawns with no target (nullptr or Entity::Null)

Expected interfaces
- set the camera position
- set the camera rotation
- set the camera zoom (force a min/max value and provide a default value)
- set the camera's type (perspective/ortho)
- set the camera near and far clip (force a min/max value and provide a default value)
- set the camera target entity (can set to nullptr or Entity::Null to disable)
- set the camera target position (overload of the above function to pass in a position)
- halt all camera movement (instantly, no jitter or lerping)
- set camera smoothness (0 for instant movement to target, force a min/max value)

**Comment by DireVision** [comment]
Default behavior has yet to be confirmed but the rest of the interfaces are present
