### ISSUE TITLE
rpg wasd movement implementation

### ISSUE THREAD

**Issue by touchportyl** [WLVerse/FlexEngine#49]
Character controller component with an accompanying system to convert inputs to wasd movement.

**Comment by DireVision** [comment]
CharacterInput is the component that does this. An example of it being updated in the system looks like this. This is in overworld.cpp as of 31/10/2024

`for (auto& entity : FlexECS::Scene::GetActiveScene()->CachedQuery<CharacterInput>())
{
    entity.GetComponent<CharacterInput>()->up = Input::GetKey(GLFW_KEY_W);
    entity.GetComponent<CharacterInput>()->down = Input::GetKey(GLFW_KEY_S);
    entity.GetComponent<CharacterInput>()->left = Input::GetKey(GLFW_KEY_A);
    entity.GetComponent<CharacterInput>()->right = Input::GetKey(GLFW_KEY_D);
}`
